apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJkbWRoY20xaGMyZzZaMmh3WDNwUFdrTjFUbkpHVUZoaGJWaHRTVEZvUmpSSldUVXdWR2R0VkcxMFRqSlRTemRYUXc9PSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson
